// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: StiMeter

#include "ui.h"
#include "ui_helpers.h"
#include "boot/boot_screen.h"

///////////////////// VARIABLES ////////////////////

// EVENTS
lv_obj_t *ui____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// BOOT SEQUENCE ////////////////////
//
// Timeline (ms from boot_start):
//   t=  400  logo starts fading in  (800 ms fade)
//   t= 1200  logo fully visible
//   t= 3700  boot_finish_timer_cb fires → 800 ms fade to main screen
//   t= 4500  main screen fully visible
//
// Total splash time visible: ~2.5 s.  Adjust BOOT_HOLD_MS to taste.

#define BOOT_HOLD_MS 3700

static void boot_finish_timer_cb(lv_timer_t *t)
{
    lv_timer_del(t);
    boot_finish(ui_Screen1);
    startup_sweep_begin();   // kick off the gauge sweep on the main screen
}

///////////////////// SCREENS ////////////////////

void ui_init( void )
{
    lv_disp_t *dispp = lv_disp_get_default();
    lv_theme_t *theme = lv_theme_default_init(dispp,
        lv_palette_main(LV_PALETTE_BLUE),
        lv_palette_main(LV_PALETTE_RED),
        true, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);

    // Build main screen (not loaded yet — boot screen loads first)
    ui_Screen1_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);

    // Show boot splash, then transition to main after BOOT_HOLD_MS
    boot_screen_create();
    boot_start();

    lv_timer_t *boot_timer = lv_timer_create(boot_finish_timer_cb, BOOT_HOLD_MS, NULL);
    lv_timer_set_repeat_count(boot_timer, 1);
}

void ui_destroy( void )
{
    ui_Screen1_screen_destroy();
}
